application: scenic-arc
version: 1
runtime: go
api_version: go1
default_expiration: "5m"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.git)/.*
- ^src
- ^py

builtins:
- datastore_admin: on
- remote_api: on
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static
  secure: optional

- url: /api/newfile
  script: _go_app

# Backend stuff.
- url: /(async|batch|resend|update|admin).*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  login: required
